### ISSUE TITLE
FDK-Header

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/fdk-community-service#10]

**Comment by shenluna** [comment]
Lenkene i headeren går til prod, bør gå til miljøet man er i.
![image](https://user-images.githubusercontent.com/73637969/114982919-4e3c8380-9e90-11eb-99b7-8a18990a4972.png)

**Comment by shenluna** [comment]
Flere lenker som fremdels går mot prod som bør gå til miljøet man er i, gjelder både i header og footer
![image](https://user-images.githubusercontent.com/73637969/115669659-cd2a3400-a348-11eb-9ed5-a4d6cf6ea3b9.png)

**Comment by matsjs** [comment]
Fikses i #21

**Comment by shenluna** [comment]
Nå går alle lenkene til feks: https://community.staging.fellesdatakatalog.digdir.no/env/organizations
![image](https://user-images.githubusercontent.com/73637969/116043657-3cb56180-a670-11eb-8165-074407826b9d.png)

**Comment by shenluna** [comment]
Testet OK
