### ISSUE TITLE
SMTP for Datalandsbyen

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#105]

**Comment by valosnah** [comment]
Digdir har bekreftet at connectoren ikke kan settes opp til å lytte på port 587, kun 25
GCP støtter ikke å sende epost over port 25, med mindre vi oppretter et gmail-relay.
For å kunne sette opp et relay, må vi aktivere en betalt workspace-tjeneste:
https://workspace.google.com/pricing.html

Kaller inn til et møte for å drøfte veien videre.
