### ISSUE TITLE
Mulighet til å velge profilbilde i form av avatar

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#106]
Se behov: https://github.com/Informasjonsforvaltning/behov/issues/603

Vi har ikke støtte for å laste opp eget bilde av seg selv, men man ønsker å gi brukere tilgang til å gjøre profilen sin mer personlig ved å tilby mulighet til å velge en avatar.

Er dette mulig med nodeBB?

**Comment by matsjs** [comment]
Dette er fikset i NodeBB's instillinger i prod og staging.
