### ISSUE TITLE
Mulighet til å opprette subkategorier

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#107]
Se behov: https://github.com/Informasjonsforvaltning/behov/issues/601

I admin-panelet til NodeBB gir den inntrykk for at man kan opprette subkategorier. 

1. Når man oppretter en ny kategori og setter foreldrekategori ved opprettelse får man en feilmelding.
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/ec334906-7723-4cfa-aeb2-f9c156dc1c51)
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/5efc1534-ef36-41b1-8e32-62d15ec19f85)

2. Hvis man først oppretter en kategori og setter foreldrekategori etterpå. Blir denne kategorien borte fra menyen.
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/da9133f6-c28a-4282-bc40-62caa2af210f)
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/3d6d5617-bc7f-47aa-8499-a6babf9e530f)
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/726eef07-4ebe-4247-bed7-529073476942)

**Comment by matsjs** [comment]
@valosnah fikset cloud armor, testet å funke i staging

**Comment by shenluna** [comment]
Testet OK
