### ISSUE TITLE
Kalender - språk og visning av tekst ved hovering

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#111]
Eksempel fra kalenderen hvor mye av teksten er på engelsk bortsett fra "lukk", bør oversette alt til norsk.
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/1a4f1135-2044-45ec-a3da-a6f3d008cdb4)

Når man hovrer over teksten i kalenderen forventes det at man får lest hele teksten, men denne blir helt blank.
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/07c6938e-4e2b-451c-8204-a1fc497fcda1)

**Comment by matsjs** [comment]
Fikset av @jeffreiffers i https://github.com/pitaj/nodebb-plugin-calendar/commit/2b9893dad12ee59bce494fe0fb24342f66cf9e67.

Kommer i neste versjon av pluginen.
