### ISSUE TITLE
Flytt avkrysningsboks ned i bruksvilkår i Data

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#141]
![Screenshot 2021-12-10 at 12.20.04.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/71975f37-8252-420d-ae82-6658211c5466)

Det er flere brukere som syntes det er vanskelig å finne begge avkrysningsboksene når man registrerer seg i Datalandsbyen.

I første omgang ønsker vi å flytte begge boksene ned slik at det blir enklere for brukerene våre å finne dem.
På sikt vil vi se på å utheve de mer i designet.

**Comment by jeffreiffers** [comment]
![image](https://user-images.githubusercontent.com/430997/147237748-e738dcbf-3a5d-4901-acdc-062c4774014e.png)

**Comment by shenluna** [comment]
Testet ok i staging
