### ISSUE TITLE
Oppgrader NodeBB til v2

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#162]

**Comment by livarb** [comment]
Er det på denne saka eg skal gje tilbakemelding?
Testa NodeBB i staging no, og ser at kalender-oppføringar ser bra ut, og at bakgrunnsfargen på varslingar er leseleg.

**Comment by valosnah** [comment]
@livarb Det var i dette: https://github.com/Informasjonsforvaltning/fdk-community-service/issues/159

Flytter dette issuet tilbake til TODO, til kalenderfolka har oppdatert pluginen sin.

**Comment by pooriamehregan** [comment]
Lenke til `nodebb-plugin-calendar` : https://github.com/pitaj/nodebb-plugin-calendar/issues/152
