### ISSUE TITLE
Oppdatere ikoner

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-community-service#181]
Oppdatere ikoner jf. designskissene: https://eggedosis.github.io/fdk-design/menu.html

Ikonene kommer med ny versjon av fdk-kit.

**Comment by KjerstiSteien** [comment]
@matfuru kan du vurdere om dette fortsatt er en relevant oppgave?

**Comment by KjerstiSteien** [comment]
Vi løser ikke dette nå. Lukker saken.
