### ISSUE TITLE
Community frontend pirk

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#21]
- [x] Fiks z-index profildropdown

- [x] Navn ved forrige innlegg på fremside/ kategorier

- [x] Footer spretter opp når man forfatter kommentar

- [x] Bør ha med notifications

- [x] Feil tekstfarge i mobil-navbar

- [x] Spacing på knapper recent & popular

- [x] Reply knapp henger igjen hvis man lager kommentar på en tråd uten kommentarer

- [ ] ~~Statisk mappe for kategoriikoner/ fikse fillagring ~~

- [x] Lenker i header og footer peker på feil miljø

- [x] Knapper har feil farge når logget ut

- [x] Varselikon er ikke som i designet 

- [ ] ~~Farger bak ikoner bør være hvit !important~~

Ved klikk på profilbilde blir menyen lagt under 'Nytt emne'-linjen under menyvalgene uleste, seneste og populære 
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/05239d41-e938-46b7-8f69-be5adce55362)

**Comment by lillelars** [comment]
Samme gjelder notifications
![image](https://user-images.githubusercontent.com/39513382/115021431-3da20280-9ebc-11eb-9a0b-53d083f36758.png)

**Comment by matsjs** [comment]
Skal vi beholde notifications @lillelars ?

**Comment by shenluna** [comment]
Testet og verifisert
