### ISSUE TITLE
Feilmelding popper opp stadig vekk

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#37]
Denne feilmeldingen dukker stadig vekk opp i community i ca ett sekund før den blir borte igjen.

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/237b37b1-d736-407e-8c43-93a4d7e221cd)

**Comment by matsjs** [comment]
Mulig løsning: https://github.com/NodeBB/NodeBB/issues/5537

**Comment by shenluna** [comment]
Har ikke opplevd feilmelding etter fix. Lukker saken.
