### ISSUE TITLE
NodeBB OIDC pålogging (SSO)

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-community-service#4]
1. Autentisering
2. Rollestyring 
3. Inspisere databasen om hvilken opplysninger som blir lagret (ifm juridisk)

Pålogging via Felles brukerhåndtering

**Comment by jeffreiffers** [comment]
Login med admin eller felles brukerhåndtering:
https://community.staging.fellesdatakatalog.digdir.no/login

Login med felles brukerhåndtering og når du allerede har sesjon fra før (for eks registrering):
https://community.staging.fellesdatakatalog.digdir.no/auth/fdk-sso

Følgende som mangler:

1. Full navn
2. Plasser bruker i riktig gruppe

**Comment by shenluna** [comment]
Testet OK
