### ISSUE TITLE
Oppdatere frontend for grupper

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#46]
- [ ] Header og banner går inn i hverandre under grupper
- [ ] Oversikten over grupper mangler avrundede hjørner

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/4778b2e9-f501-4b02-b15e-e08ab45de05e)
![image](https://user-images.githubusercontent.com/73637969/116400422-4da9d280-a82a-11eb-92bb-13a214e2243f.png)

**Comment by jeffreiffers** [comment]
Kan denne lukkes?

**Comment by shenluna** [comment]
Lukker saken, da dette er løst.
