### ISSUE TITLE
"Slett meg selv" - bruker vises fortsatt

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-community-service#52]
Kan forveksles med "Utslett megselv"... Men det er det altså ikke.

Etter at Joachim har slettet brukeren sin skal den ikke vises her.

- [ ] Se på nodeBB innstillinger om dette kan justeres

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/dddbfa8c-cb8b-4399-8eac-32ee1c5a352a)

**Comment by jeffreiffers** [comment]
Man får ikke slette brukere som er administrator. En annen administrator kan slette brukeren.

**Comment by jeffreiffers** [comment]
Kan jeg lukke saken?

**Comment by shenluna** [comment]
Ingen problemer å slette vanlige brukere, aktiviteten i forumet vil fremdeles syntes men det er ingen knytninger til tidligere bruker
![image](https://user-images.githubusercontent.com/73637969/117049778-e651be00-ad14-11eb-8ec9-4b7b08aa9eff.png)
