### ISSUE TITLE
Brukernavn kan endres i community og håndter duplikater

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-community-service#56]

**Comment by shenluna** [comment]
Får feilmelding når man prøver å endre til brukernavn som allerede finnes, men man får ikke lov til å prøve andre brukernavn før man tar refresh
![image](https://user-images.githubusercontent.com/73637969/117133444-8a367a80-ada4-11eb-8917-282e7f14856e.png)

**Comment by shenluna** [comment]
Mulig å endre brukernavn og får feilmelding ved duplikater. Laget egen sak om refresh etter endring til eksisterende brukernavn. https://github.com/Informasjonsforvaltning/fdk-community-service/issues/60
