### ISSUE TITLE
Feilmelding ved klikk på registrer/logg inn

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#59]
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/a1c2fb4e-a701-4849-a824-aa1a2a9e451e)

**Comment by matsjs** [comment]
@shenluna Får ikke gjenskapt problemet - skjer det fortsatt? Hva gjør du for at det skal skje?

**Comment by shenluna** [comment]
@matsjs Jeg får heller ikke gjenskapt problemet lenger, lukker saken.
