### ISSUE TITLE
Gjennomgående styling

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/fdk-community-service#6]
https://www.figma.com/proto/RD17kpqqWbM5I3fZOPKpHB/Community?node-id=1799%3A8190&viewport=2363%2C120%2C1.5300536155700684&scaling=scale-down&page-id=0%3A1
- [x] Farger

- [x] Fonter

- [x] Kategori cards

- [x] Menybar

**Comment by shenluna** [comment]
Testet ok
