### ISSUE TITLE
Styling hovedside

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/fdk-community-service#7]
- [x] Style menybar

- [x] Tekster menybar

- [x] Community introduksjon/ bilde

- [x] Avrundede kanter

- [x] Forstørre ikoner

**Comment by shenluna** [comment]
Logoene på hovedsiden mangler
![image](https://user-images.githubusercontent.com/73637969/115512967-d3ee7380-a282-11eb-8838-ce5a971c14df.png)

**Comment by shenluna** [comment]
Testet ok
