### ISSUE TITLE
Vise og finne brukervilkår

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#71]
Se behov: https://github.com/Informasjonsforvaltning/behov/issues/594

Det er et ønske om å lett kunne finne tilbake til brukervilkårene man har akseptert og kunne lese de på nytt.

- [x] Legge til lenke med brukervilkår i "Your Rights & Consent"
- [x] Gjøre det enkelt for en bruker å finne brukervilkårene

**Comment by jeffreiffers** [comment]
![Uploading image.png…]()
