### ISSUE TITLE
Oversikt over møter og arrangementer - kalender

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#74]
Se behov: https://github.com/Informasjonsforvaltning/behov/issues/595

Det er et ønske om å lett kunne få en oversikt over kommende møter og arrangementer.
Det er for øyeblikket lagt til en kalenderfunksjon for dette.

Per dags dato kan man opprette 'events' fra alle kategorier. Vi ønsker å begrense det til kun kategorien møter og arrangementer.
- [x] Begrens mulighet til å opprette events til kategorien "Møter og arrangementer"

**Comment by jeffreiffers** [comment]
Admin for lov å opprette hendelser i alle kategorier. Registrerte brukere får kun lov å opprette hendelser under **Møter og arrangementer**

**Comment by shenluna** [comment]
Testet OK
