### ISSUE TITLE
Feilmelding ved trykk på "Calendar"

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#76]
Ved trykk på "Calendar" får man følgende feilmelding:
"Startsiden" i feilmeldingen fungerer heller ikke.
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/b27c2597-b8c2-44e9-8ff2-8e7f8b96dc23)

**Comment by matsjs** [comment]
Calendar skal funke som forventet.

Feillenkene stammer fra en feil i oversettelsen: Lenkeadressen er "" i stedet for "/". Dette har jeg fikset i transifex som er lokaliseringsprogramvaren NodeBB bruker. Denne oversettelsen må godkjennes manuelt før den kommer i løsningen vår, men den er på vei.
