### ISSUE TITLE
Rutine for sletting av brukere

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-community-service#87]
Se behov: https://github.com/Informasjonsforvaltning/behov/issues/599

Per dags dato blir det opprettet brukerkonto før en bruker har akseptert brukervilkår og samtykke.
Vi ønsker at disse brukerene både blir slettet automatisk og evt. ved en manuell rutine.

Rutine for sletting:
Sletter etter 14. dager om vilkår ikke er akesptert
Slette etter ett år om bruker er inaktiv

**Comment by jeffreiffers** [comment]
Vi kan sette opp en cronjob i nodebb containeren som inneholder to skripter:

1. Finn og slett alle brukere som har vært inaktiv 1 år (ikke meldinger)
2. Finn og slett alle brukere som ikke har godkjent vilkårene og har blitt opprettet > 14 dager siden

Vi bruker REST APIet til NodeBB og curl.

**Comment by stigbd** [comment]
Bra forslag. Om 1 år og 14 dager er korrekt, må feks @ChristianeFrhlich bestemme.

**Comment by ChristianeFrhlich** [comment]
1 år og 14 dager er OK for en manuell rutine, slik det er i dag. Vi må jo løpende kontrollere om brukere har godtatt, og av den grunn behøver vi tid til å se setter. Skal dette derimot automatiseres, burde intervallet for 14 dager være mye kortere. Det er fordi vi behandler opplysninger selv om brukeren ikke har samtykket til det. I praksis burde ikke det skje.
