### ISSUE TITLE
Styling innleggside

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/fdk-community-service#9]
- [x] Tittel

- [x] Cards av innlegg og svar

- [x] Knapper

**Comment by shenluna** [comment]
Noen småting
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
![image](https://user-images.githubusercontent.com/73637969/115394252-e31de480-a1e2-11eb-9846-58bbb7815ee3.png)

**Comment by matsjs** [comment]
1. Fikset.
2. Dette er navnet på kategorien. Kan endres i admin-panel
3. Fikset.
4. Rekkefølge på navigasjon endres i admin/settings/navigation
5. Rekkefølge på navigasjon endres i admin/settings/navigation
6. Dette er del av issue #15: https://app.zenhub.com/workspaces/fdk---felles-datakatalog-5c61461c801d5a1030316315/issues/informasjonsforvaltning/fdk-community-service/15
7. Disse skal styles, venter på design
8. Fikset.

**Comment by shenluna** [comment]
Testet Ok, lukker saken
